version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    timezone: America/Chicago
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
